FROM ruby:3.2

RUN apt-get update && apt-get install -y \
  build-essential \
  libsqlite3-dev \
  sqlite3 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN bundle install

CMD ["ruby", "crawler.rb"]